spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 66666666
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
debug: true
server:
  port: 8888
